name: Generate snake animation

on:
  schedule: # execute every 12 hours
    - cron: "0 */12 * * *" # Corrigido: executa a cada 12 horas
  workflow_dispatch:
  push:
    branches:
      - main # Corrigido: usa a branch principal do seu repositório

jobs:
  generate:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Generate snake SVGs
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: EdesioRodrigues
          outputs: |
            dist/snake-light.svg?palette=github-light
            dist/snake-dark.svg?palette=github-dark

      - name: Push SVGs to the output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
