name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *" # Executa todo dia à meia-noite
  workflow_dispatch: # Permite executar manualmente

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: Platane/snk@v3
        with:
          github_user_name: seu-usuario
          outputs: |
            output/github-contribution-grid-snake.svg
      - uses: actions/upload-artifact@v3
        with:
          name: snake
          path: output/
      - name: Push to branch
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          git add output/
          git commit -m "Update snake animation" || echo "No changes to commit"
          git push
